### ISSUE TITLE
400 Bad Request when connecting with VMware PowerCLI 11.0.0 build 10380590

### ISSUE THREAD

**Issue by jones-g** [nimmis/docker-vcsim#1]
I have your vcsim Docker image running as a test but am unable to connect to it via PowerCLI to test PowerCLI connections and scripts.

I'm running on the nimmis/vcsim:latest version on an Ubuntu VM based Docker host.
If I browse https://<ip>/about I get the correct list of available end points.
If I use govc it can also connect no problem.

My bet is that PowerCLI 11.0 is doing a request that is not implemented but I am unaware of how to check which request is failing to get closer to the issue.

Any ideas?

**Comment by jsonofcourse** [comment]
I found that I was getting the same error with Vmware.PowerCLI 11.2.0.12483638. After upgrading to 11.4.0.14413515 (current release as of this message) I was able to connect without any issue.

**Comment by nimmis** [comment]
Thanks @jsonofcourse for solving this issue
