### ISSUE TITLE
vsphere not running after latest build

### ISSUE THREAD

**Issue by mdelapenya** [nimmis/docker-vcsim#2]
The entrypoint references to a flag that is not existing anymore. It seem the flag `httptest.serve` flag was removed here: https://github.com/vmware/govmomi/pull/1439/files

**Comment by mdelapenya** [comment]
It would be great too if not using `latest` only, and having a version schema not to be affected by changes in upstream

**Comment by Satak** [comment]
Here is an alternative vcsim docker container image that I created. It uses the latest `-l` flag: https://hub.docker.com/r/satak/vcsim
